#!/usr/bin/env python3
"""
scrape_ai_ground_truth.py
─────────────────────────
Build an AI-audio GROUND-TRUTH dataset by searching YouTube with yt-dlp and
keeping ONLY tracks whose uploader explicitly declares the audio is AI-generated.

Positive-only validation
─────────────────────────
No negative filtering ("not AI").  Instead a strict regex WHITELIST (Python `re`)
scans each video's title + description + tags for an explicit AI declaration.
Key safety properties (see self-test at the bottom):
  • \b word boundaries so `@suno`, `#suno`, `suno.com`, `SunoAI` all match…
  • …but `studio` / `audio` NEVER trigger the `udio` rule (no substring hits).
If no definitive positive match is found, the video is skipped.

Metadata-only staging (downloads DISABLED)
───────────────────────────────────────────
  1. `extract_flat=True` search — cheap enumeration of candidate results.
  2. per-video `extract_info(download=False)` — flat mode does NOT expose the
     description / tags / duration we need, so we pull full metadata (still no
     audio download) for the two gates below.
  3. GATE 1 — regex AI whitelist on title + description + tags.
     GATE 2 — duration window (MIN_DURATION..MAX_DURATION s) to drop tutorials
              and podcasts.
  4. Videos passing BOTH gates are STAGED (not downloaded) to a review file:
         verified_ai_links.txt   (project root)
     one line each:  [seconds]s | [Title] | [URL]
  The MP3-download pipeline is commented out (see download_mp3 below).

Usage:
    python3 scrape_ai_ground_truth.py                       # default 4 queries x 20
    python3 scrape_ai_ground_truth.py --per-query 30
    python3 scrape_ai_ground_truth.py --queries "Suno AI full song" "Udio track"
    python3 scrape_ai_ground_truth.py --selftest            # regex validation only
"""

import os, re, sys, argparse
import yt_dlp                                    # download disabled; used for search/metadata only

HERE       = os.path.dirname(os.path.abspath(__file__))
ROOT       = os.path.dirname(HERE)                             # project root
OUT_DIR    = os.path.join(HERE, "data", "ground_truth_ai")    # (unused: MP3 download disabled)
LINKS_FILE = os.path.join(ROOT, "verified_ai_links.txt")      # staged links for manual review

# Duration acceptance window (seconds).  Rejects tutorials / podcasts (too long)
# and stray clips (too short), keeping song-length audio only.  Inclusive bounds.
MIN_DURATION = 90
MAX_DURATION = 300

# Explicit, targeted search queries (top-N results enumerated per query).
DEFAULT_QUERIES = [
    "AI generated music",
    "Suno AI full song",
    "Udio track",
    "AI music official audio",
]

# ── Positive-only AI whitelist ─────────────────────────────────────────────────
# Each entry: (compiled pattern, human-readable keyword for logging).
# Notes on the tricky ones:
#   \budio(...)  -> the leading \b demands a word boundary immediately BEFORE 'u',
#                   which does NOT exist inside "st|udio" or "a|udio" (t/a are word
#                   chars), so `studio` and `audio` can never match.  A boundary
#                   DOES exist after '@', '#', '.', or whitespace, so "@udio",
#                   "#udio", "udio.com" all match.
#   suno|udio (?:[\s.\-_]*ai)?  -> also catches the very common glued forms
#                   "SunoAI" / "suno.ai" / "udio-ai" while still respecting \b.
_FLAGS = re.IGNORECASE
AI_PATTERNS = [
    (re.compile(r"\bsuno(?:[\s.\-_]*ai)?\b", _FLAGS),                         "suno"),
    (re.compile(r"\budio(?:[\s.\-_]*ai)?\b", _FLAGS),                         "udio"),
    (re.compile(r"\bai[\s.\-_]*generated\b", _FLAGS),                         "ai generated"),
    (re.compile(r"\bgenerated[\s.\-_]*(?:by|with|using)[\s.\-_]*ai\b", _FLAGS),"generated by ai"),
    (re.compile(r"\bai[\s.\-_]*music\b", _FLAGS),                             "ai music"),
    (re.compile(r"\bai[\s.\-_]*song\b", _FLAGS),                              "ai song"),
    (re.compile(r"\bai[\s.\-_]*(?:cover|vocals?|track)\b", _FLAGS),           "ai cover/vocals"),
    (re.compile(r"\bmade[\s.\-_]*with[\s.\-_]*(?:suno|udio|ai)\b", _FLAGS),   "made with ai"),
]


def find_ai_declaration(text: str):
    """Return the first matched keyword (str) or None if no explicit AI claim."""
    if not text:
        return None
    for pattern, keyword in AI_PATTERNS:
        if pattern.search(text):
            return keyword
    return None


# ── Step 1a: flat search (metadata only) ───────────────────────────────────────
def search_candidates(query: str, n: int):
    """Enumerate up to `n` search results as flat metadata (id/title/url)."""
    opts = {"quiet": True, "no_warnings": True, "extract_flat": True, "skip_download": True}
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(f"ytsearch{n}:{query}", download=False)
    return [e for e in (info.get("entries") or []) if e]


# ── Step 1b: full metadata (still NO download) for description + tags ──────────
def fetch_metadata(url: str) -> dict:
    """extract_flat omits description/tags, so pull full metadata (download=False)."""
    opts = {"quiet": True, "no_warnings": True, "skip_download": True, "noplaylist": True}
    with yt_dlp.YoutubeDL(opts) as ydl:
        info = ydl.extract_info(url, download=False)
    return {
        "title":       info.get("title") or "",
        "description": info.get("description") or "",
        "tags":        info.get("tags") or [],
        "uploader":    info.get("uploader") or "",
        "duration":    info.get("duration"),          # seconds (float/int) or None
        "webpage_url": info.get("webpage_url") or url,
    }


# ── Step 2: download pipeline — DISABLED ──────────────────────────────────────
# Immediate downloading is turned off.  Verified links are staged to a text file
# for manual review instead (see main()).  The MP3-download implementation is
# retained below but COMMENTED OUT so nothing is fetched to disk.
#
# def download_mp3(url: str, out_dir: str) -> str:
#     """Convert bestaudio -> 192 kbps MP3 into out_dir. Returns the .mp3 path."""
#     opts = {
#         "quiet": True, "no_warnings": True, "noplaylist": True,
#         "format": "bestaudio/best",
#         "outtmpl": os.path.join(out_dir, "%(id)s.%(ext)s"),
#         "restrictfilenames": True,
#         "postprocessors": [{
#             "key": "FFmpegExtractAudio",
#             "preferredcodec": "mp3",
#             "preferredquality": "192",
#         }],
#     }
#     with yt_dlp.YoutubeDL(opts) as ydl:
#         info = ydl.extract_info(url, download=True)
#     return os.path.join(out_dir, f"{info['id']}.mp3")


def _load_existing_urls(path: str) -> set:
    """URLs already staged in a prior run, so re-runs don't append duplicates."""
    urls = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for ln in f:
                parts = ln.rstrip("\n").split(" | ")
                if len(parts) >= 3:
                    urls.add(parts[-1].strip())
    return urls


# ── Main pipeline ──────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description="Stage explicitly-declared AI tracks from YouTube to a review file.")
    ap.add_argument("--queries", nargs="+", default=DEFAULT_QUERIES)
    ap.add_argument("--per-query", type=int, default=20, help="results to enumerate per query")
    args = ap.parse_args()

    print("=" * 72)
    print("AI ground-truth scraper — regex whitelist + duration filter -> staged links")
    print(f"  Queries        : {len(args.queries)}  x  {args.per_query} results each")
    print(f"  Duration window: {MIN_DURATION}-{MAX_DURATION}s (inclusive)")
    print(f"  Staging file   : {LINKS_FILE}")
    print(f"  Downloads      : DISABLED (staging links for manual review only)")
    print("=" * 72)

    seen_ids       = set()
    existing_urls  = _load_existing_urls(LINKS_FILE)
    staged = skip_regex = skip_dur = dup = 0

    # Append mode: verified links accumulate across runs (dupes are filtered).
    links_fh = open(LINKS_FILE, "a", encoding="utf-8")

    for q in args.queries:
        print(f"\n🔎 Searching: \"{q}\"")
        try:
            candidates = search_candidates(q, args.per_query)
        except Exception as exc:
            print(f"   [search error] {exc}", file=sys.stderr)
            continue
        print(f"   {len(candidates)} candidate(s) returned.")

        for entry in candidates:
            vid = entry.get("id")
            url = entry.get("url") or entry.get("webpage_url") or (f"https://www.youtube.com/watch?v={vid}" if vid else None)
            if not url or vid in seen_ids:
                continue
            seen_ids.add(vid)

            # ── Metadata-only probe (title + description + tags + duration) ────
            try:
                meta = fetch_metadata(url)
            except Exception as exc:
                print(f"   [meta error] {entry.get('title','?')[:50]}: {exc}", file=sys.stderr)
                continue

            title    = meta["title"][:70]
            duration = meta["duration"]
            web_url  = meta["webpage_url"]

            # ── Gate 1: positive-only AI whitelist ────────────────────────────
            haystack = " ".join([meta["title"], meta["description"], " ".join(meta["tags"])])
            keyword = find_ai_declaration(haystack)
            if keyword is None:
                skip_regex += 1
                print(f"   ⏭️  Skipped: No explicit AI declaration in text — \"{title}\"")
                continue

            # ── Gate 2: duration window (filters tutorials / podcasts) ─────────
            if duration is None or not (MIN_DURATION <= duration <= MAX_DURATION):
                skip_dur += 1
                shown = f"{int(duration)}s" if duration else "unknown length"
                print(f"   ⏭️  Skipped: Failed duration window ({shown})")
                continue

            # ── Passed BOTH gates -> stage link to text file (no download) ─────
            if web_url in existing_urls:
                dup += 1
                print(f"   ↩️  Already staged (duplicate) — \"{title}\"")
                continue

            line = f"{int(duration)}s | {meta['title']} | {web_url}"
            links_fh.write(line + "\n")
            links_fh.flush()
            existing_urls.add(web_url)
            staged += 1
            print(f"   ➕ Added to txt: \"{title}\"  [matched: '{keyword}', {int(duration)}s]")

    links_fh.close()

    print("\n" + "=" * 72)
    print(f"DONE — {staged} verified AI link(s) staged to {os.path.basename(LINKS_FILE)}.")
    print(f"  Skipped (no AI declaration) : {skip_regex}")
    print(f"  Skipped (duration window)   : {skip_dur}")
    print(f"  Skipped (already staged)    : {dup}")
    print(f"Review file: {LINKS_FILE}")
    print("=" * 72)


# ── Self-test: the adversarial regex cases the spec calls out ──────────────────
def _selftest():
    must_match = [
        "Made with Suno",           # suno
        "check @suno on twitter",   # @suno
        "#suno #aimusic",           # #suno
        "generated on suno.com",    # suno.com
        "SunoAI banger",            # glued SunoAI
        "created in Udio",          # udio
        "@udio release",            # @udio
        "udio.com track",           # udio.com
        "this is an AI generated song",   # ai generated
        "AI-generated instrumental",      # ai-generated
        "full ai music mix",              # ai music
        "generated by AI",                # generated by ai
        "made with ai",                   # made with ai
    ]
    must_not_match = [
        "recorded in my home studio",     # studio  -> must NOT hit \budio\b
        "high quality audio only",        # audio   -> must NOT hit \budio\b
        "professional studio audio mix",  # both traps in one string
        "a relaxing piano piece",         # nothing AI
        "live acoustic session",          # 'acoustic' contains no whole-word trap
        "brainstorm session music",       # 'ai' inside 'brain' must not trigger
    ]
    ok = True
    for t in must_match:
        kw = find_ai_declaration(t)
        flag = "PASS" if kw else "FAIL"
        if not kw: ok = False
        print(f"  [{flag}] MATCH expected     | {t!r:45s} -> {kw}")
    for t in must_not_match:
        kw = find_ai_declaration(t)
        flag = "PASS" if kw is None else "FAIL"
        if kw is not None: ok = False
        print(f"  [{flag}] NO-match expected  | {t!r:45s} -> {kw}")
    print("\nSELF-TEST:", "ALL PASSED ✅" if ok else "FAILURES ❌")
    return ok


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(0 if _selftest() else 1)
    main()
