#!/usr/bin/env python3
"""
youtube_nlp_extractor.py  —  strict-Regex text analysis for Late Fusion
────────────────────────────────────────────────────────────────────────
Replaces the last two mock slots in fusion_aggregator.py with real text
parsing built ONLY on the Python standard library (`re`). No LLM APIs, no
heavy NLP dependencies.

1. scan_text_for_ai_markers(text_content)
   Context-aware description/tag scanner. A target keyword counts as an AI
   marker only when it is NOT negated: the compiled pattern carries a chain of
   negative lookbehinds for the immediately-preceding modifier, and a ~20-char
   look-back window catches negations sitting a few words earlier
   ("without any of that suno stuff"). Returns 1.0 on a clean hit, else None.

2. analyze_comment_threads(comments_list)
   Comment-suspicion heuristic: density ratio of comments containing
   suspicion keywords over total comments, clamped to [0.0, 1.0].
   Empty/invalid input returns None (signal excluded from fusion).

Self-test:  python3 youtube_nlp_extractor.py --selftest
"""

import re
import sys

# ── 1. Context-aware description scanner ───────────────────────────────────────
TARGET_KEYWORDS = ["suno", "udio", "elevenlabs", "ai cover", "ai generated",
                   "voice model"]
NEGATION_MODIFIERS = ["not", "no", "without", "versus", "vs", "against",
                      "fake", "spot"]
NEGATION_WINDOW = 20          # chars scanned backwards from a keyword hit

# Multi-word keywords tolerate space / hyphen / underscore separators
# ("ai generated", "AI-generated", "ai_generated" all match). \b guards stop
# substring bleed: "studio"/"audio" never trip "udio", "sunout" never "suno".
_TARGET_PATTERN = r"\b(?:" + "|".join(
    re.escape(k).replace(r"\ ", r"[\s\-_]+") for k in TARGET_KEYWORDS) + r")\b"

# Chain of fixed-width negative lookbehinds: kills the tightest form of
# negation ("not suno", "vs udio") inside the pattern itself.
_LOOKBEHINDS = "".join(rf"(?<!\b{re.escape(w)} )" for w in NEGATION_MODIFIERS)

TARGET_RE   = re.compile(_LOOKBEHINDS + _TARGET_PATTERN, re.IGNORECASE)
NEGATION_RE = re.compile(r"\b(?:" + "|".join(map(re.escape, NEGATION_MODIFIERS))
                         + r")\b", re.IGNORECASE)


def scan_text_for_ai_markers(text_content):
    """
    Scan free text (description / title / tags blob) for AI-platform markers.

      1.0   -> a target keyword found NOT preceded by a negation modifier
               within ~NEGATION_WINDOW chars (strong AI signal)
      None  -> no keyword, keyword only in negated context, or empty input
    """
    if not text_content or not isinstance(text_content, str):
        return None
    for m in TARGET_RE.finditer(text_content):
        window = text_content[max(0, m.start() - NEGATION_WINDOW):m.start()]
        if NEGATION_RE.search(window):
            continue                       # negated within the window — ignore
        return 1.0
    return None


# ── 2. Comment-suspicion heuristic ─────────────────────────────────────────────
SUSPICION_KEYWORDS = ["robotic", "synthetic", "fake vocals", "generated by",
                      "prompt", "ai generated", "text to speech"]

SUSPICION_RE = re.compile(r"\b(?:" + "|".join(
    re.escape(k).replace(r"\ ", r"[\s\-_]+") for k in SUSPICION_KEYWORDS)
    + r")\b", re.IGNORECASE)


def analyze_comment_threads(comments_list):
    """
    Basic suspicion density over a comment thread.

      float in [0.0, 1.0] -> (# comments containing a suspicion keyword) /
                             (total valid comments), clamped
      None                -> empty / invalid input (signal excluded)
    """
    if not comments_list or not isinstance(comments_list, (list, tuple)):
        return None
    comments = [c for c in comments_list if isinstance(c, str) and c.strip()]
    if not comments:
        return None
    suspicious = sum(1 for c in comments if SUSPICION_RE.search(c))
    return max(0.0, min(1.0, suspicious / len(comments)))


# ── Self-test ──────────────────────────────────────────────────────────────────
def _selftest():
    ok = True

    def check(fn, arg, want, label):
        nonlocal ok
        got = fn(arg)
        good = (got == want) or (want is not None and got is not None
                                 and abs(got - want) < 1e-9)
        if got is None or want is None:
            good = got is want
        if not good:
            ok = False
        shown = repr(arg)[:52]
        print(f"  [{'PASS' if good else 'FAIL'}] {label:<34} {shown:<54} -> {got}")

    print("── scan_text_for_ai_markers ──")
    s = scan_text_for_ai_markers
    check(s, "Made with Suno AI",                        1.0,  "plain keyword")
    check(s, "An AI-Generated love ballad",              1.0,  "hyphen separator")
    check(s, "new ELEVENLABS voice model demo",          1.0,  "case + multi keyword")
    check(s, "AI Cover of a classic",                    1.0,  "ai cover")
    check(s, "recorded in my studio",                    None, "'studio' must not trip udio")
    check(s, "official audio",                           None, "'audio' must not trip udio")
    check(s, "this is not suno",                         None, "adjacent negation (lookbehind)")
    check(s, "no udio involved here",                    None, "negation 'no'")
    check(s, "made without any suno tools",              None, "windowed negation")
    check(s, "real singer versus suno",                  None, "negation 'versus'")
    check(s, "human vs ai generated music",              None, "negation 'vs'")
    check(s, "how to spot ai generated songs",           None, "negation 'spot'")
    check(s, "we fought against ai covers... suno made this", 1.0,
          "negation >20 chars away no longer applies")
    check(s, "",                                         None, "empty string")
    check(s, None,                                       None, "None input")
    check(s, "just a normal indie song",                 None, "no keywords")

    print("── analyze_comment_threads ──")
    a = analyze_comment_threads
    check(a, [],                                          None, "empty list")
    check(a, None,                                        None, "None input")
    check(a, "not a list",                                None, "invalid type")
    check(a, [123, "", "   "],                            None, "no valid strings")
    check(a, ["nice track!", "love this", "on repeat"],   0.0,  "clean thread")
    check(a, ["sounds so robotic", "great song", "what prompt did you use?",
              "synthetic vocals fr"],                     0.75, "3/4 suspicious")
    check(a, ["this was generated by suno lol"] * 5,      1.0,  "fully suspicious")
    check(a, ["fake vocals detected"] + ["banger"] * 9,   0.1,  "1/10 density")

    print("\nSELF-TEST:", "ALL PASSED ✅" if ok else "FAILURES ❌")
    return ok


if __name__ == "__main__":
    sys.exit(0 if _selftest() else 1)
